### ISSUE TITLE
Conversion fromsvg to png possible ?

### ISSUE THREAD

**Issue by gedw99** [ajstarks/svgo#22]
I need to convert a SVG file to multiple png types.
Any idea if this can handle it or another golang library ?

**Comment by jmank88** [comment]
After trying several solutions a few months back, I ended up settling on rsvg-convert. Easy to call with os/exec.Command.

**Comment by gedw99** [comment]
Mhh bummer
Idea. Use a browser. Load the SVG and save as base64 dataurl ?

**Comment by jmank88** [comment]
I guess it would depend on your use case. For me, I was interested in speed/automation, since we render these on the fly from a live deployed server.

rsvg-convert is easy to use from the command line for one-off conversions. There are some other similar options available, depending on your OS. 

How do you plan to save the SVG from the browser?

**Comment by ajstarks** [comment]
I use the Batik SVG rasterizer or Inkscape, both on the command line.  The Inkscape rasterizer is generally faster.
