### ISSUE TITLE
Missing Translate with float parameters

### ISSUE THREAD

**Issue by emicklei** [ajstarks/svgo#9]
In my pictures, I am seeing glitches which I think are due to the rounding of floating point numbers to ints because of the function Translate(x, y int). When nesting Scaling, Translation and Rotation operations, such rounding to ints will cause this effect. My workaround is to produce the transform(...) string myself.

**Comment by stanim** [comment]
This seems to be an old issue, but a recurring one. 

I've bitten the bullet to write a program which can rewrite the current SVGo code to use floating point coordinates with different precisions (1-9). It parses the SVGo code and modifies the [syntax tree](http://golang.org/pkg/go/ast) to replace ints with floats where appropriate. No monkey patching is needed. 

Moreover it can also convert and build all the samples without any error. (Unfortunately for the samples there is a little bit of patching needed outside the [ast](http://golang.org/pkg/go/ast) , but this is done automatically.) There are probably still some hidden bugs in the conversion, but they should be fixable.

It should be no problem to keep regularly the float port in sync with the svgo library. Feel free to test the ports at: https://github.com/stanim/svgo

I am looking forward to your feedback, both from @emicklei and @ajstarks. I plan to open source also the code conversion code and to document the process, but I need to find some time to clean up the code first and write a blog post.

**Comment by swill** [comment]
@stanim This is an interesting approach, but I feel like it is going to be a bit strange to use.  If you have to use different precisions in the same file how would that work?  

I am currently using the solution I developed in #18 in production and it is working well.  I have ported the majority of the library and the remainder is pretty minimal.  My solution allows you to easily modify the precision throughout the drawing of the SVG file as needed.

**Comment by stanim** [comment]
@swill When would someone change the precision in one program? That seems unlikely. However if is a valid use case, no problem, it should be straightforward to implement in my `gofloat`convertor. I agree to do this, if  @ajstarks shares this concern.

My approach has these advantages:
- api doesn't get bloated with extra methods with all the benefits: smaller codebase to maintain, smaller compiled binaries, no need to write extra tests/examples, ...
- no strange mingling of ints and floats in one api (no program will use both `int` and `float` coordinates)
- ports for both `float32` and `float64` possible (otherwise even more need to be added: `methodF32` and `methodF64` )
- existing SVGo code does not need a rewrite of the methods, but can use the exactly the same api
- convertor could be in principal used to automatically rewrite existing SVGo code to the float api, as demonstrated by the examples
- it is not just about the effort for the one time port, but also about keeping maintenance light in the future. On the long term it will save you the cost of trying to keep everything manually in sync. So less hassle for @ajstarks, as he can delegate this task to a program.
- it uses the same lovely technology as `gofmt`, `goimports`, ..., just run:
```
gofloat github.com/ajstarks/svgo
```
- follow's Go idiomatic approach: keep (the codebase) simple, enable more
- it follows the principle: delegate everything which can be automated to code

PS This code will be used professionally to produce billboards for Amsterdam soon.

**Comment by ajstarks** [comment]
sorry to come late to the discussion.  Thanks to @swill and @stanim your contributions.  At this point I'm leaning toward the @stanim's generation method combined with a specified precision.

Please give me a few days to test...

**Comment by emicklei** [comment]
My solution (at that time) was to create a SVGF. See https://github.com/emicklei/zenna/blob/master/svgf/painter.go line 90+

**Comment by rogpeppe** [comment]
I've just come across this issue. I think that all lengths in svgo should be represented by a floating point type, to match the standard.
http://www.w3.org/TR/SVG11/types.html#DataTypeNumber

This would of course require a backwardly incompatible API change, but that would
be worth it.

An automatic AST translator could be provided to assist moving to the new API.

**Comment by ajstarks** [comment]
@stanim is the gofloat converter ready/available?

**Comment by swill** [comment]
I agree with @rogpeppe. I think that floating point should be the default and if people need to support a backwards compatible API, that is done using a similar AST type tool like what @stanim built.  It is more important that the library follows the svg standard, especially for building in new svg features as they are released.

**Comment by ajstarks** [comment]
I support the API change, question: should the new floating point version be the default and the old one be called svgoi ?

**Comment by swill** [comment]
@ajstarks yes, I think the default should be the floating point implementation. We could handle integer support in one of two ways. If we want to support it going forward, we generate svgoi from AST. Otherwise we make the current implementation available as svgoi and we put a big disclaimer that it will no longer be supported going forward, or it will only be community supported.

**Comment by stanim** [comment]
@ajstarks Yes, it was already finished in July, but always other obligations prevented from taking the time to publish the code. I need to verify if it works with the latest svgo and will upload it the latest next week. It is now possible to change the precision on the fly and non significant zeros will be stripped. (For example "5.00000000000000" will become just "5".) I have also some opinion about svgo/svgof/svgoi, but I need to go now.

**Comment by stanim** [comment]
gofloat is uploaded at https://github.com/stanim/typewriter. I'll try to add instructions this week. 

My recommendation would be also to switch to floats as a default but under a different name/repository. (gofloat would then become obsolete.) 

Otherwise you have to make the current svgo repository available in another repo or with http://labix.org/gopkg.in Afterwards it would be polite to warn at least [the relevant projects, which depend on svgo](https://godoc.org/github.com/ajstarks/svgo?importers) with an issue. 

I would be very careful to make a breaking change to such a popular package as svgo. See also: http://golang.org/doc/faq#get_version

    Packages intended for public use should try to maintain backwards compatibility 
    as they evolve. The Go 1 compatibility guidelines are a good reference here: don't 
    remove exported names, encourage tagged composite literals, and so on. If 
    different functionality is required, add a new name instead of changing an old 
    one. If a complete break is required, create a new package with a new import path.

**Comment by stanim** [comment]
I've added documentation:
https://godoc.org/github.com/stanim/typewriter
https://godoc.org/github.com/stanim/typewriter/gofloat

Let me know if something is still unclear.

PS Maybe this issue can be merged with https://github.com/ajstarks/svgo/issues/18. It seems duplicate.

**Comment by ajstarks** [comment]
First run seems to have failed:

```
$ gofloat
Open "svgo.json" ...
github.com/ajstarks/svgo -> github.com/ajstarks/svgof/svgotest:
- Empty "github.com/ajstarks/svgof/svgotest" ...
- Convert type from "int" to "float64" ...
- Fix type conflicts ...
  ... no type conflicts found.
- Format "github.com/ajstarks/svgof/svgotest" ...
- Applied 13 patches to "github.com/ajstarks/svgof/svgotest" ...
- Copy non-go files of "github.com/ajstarks/svgof/svgotest" ...
- OK

github.com/ajstarks/svgo/android -> github.com/ajstarks/svgof/svgotest/android:
- Empty "github.com/ajstarks/svgof/svgotest/android" ...
- Convert type from "int" to "float64" ...
- Fix type conflicts ...
  + /Users/ajstarks/gowork/src/github.com/ajstarks/svgof/svgotest/android/android.go:10:2: could not import github.com/ajstarks/svgof/svgotest (can't find import: github.com/ajstarks/svgof/svgotest)
  + /Users/ajstarks/gowork/src/github.com/ajstarks/svgof/svgotest/android/android.go:16:11: undeclared name: svg
- Error during fixing type conflicts
Error: fix unknown: /Users/ajstarks/gowork/src/github.com/ajstarks/svgof/svgotest/android/android.go:10:2: could not import github.com/ajstarks/svgof/svgotest (can't find import: github.com/ajstarks/svgof/svgotest)
```

**Comment by ajstarks** [comment]
I see my problem. I needed to install the generated package first.

**Comment by ajstarks** [comment]
The first commit of the floating point support is now up.  Use the import:

```import "/github.com/ajstarks/svgo/float"```

The API is identical except float64 is used for lengths and dimensions, and you can specify the number of decimal digitals in the output (SVG.Decimals).

**Comment by ajstarks** [comment]
fixed via float version of the package
